# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogProgramarTarea.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_ProgramarTarea(object):
    def setupUi(self, Dialog_ProgramarTarea):
        Dialog_ProgramarTarea.setObjectName(_fromUtf8("Dialog_ProgramarTarea"))
        Dialog_ProgramarTarea.resize(307, 722)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_ProgramarTarea.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog_ProgramarTarea)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_ConfigFecha = QtGui.QGroupBox(Dialog_ProgramarTarea)
        self.groupBox_ConfigFecha.setObjectName(_fromUtf8("groupBox_ConfigFecha"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_ConfigFecha)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_ConfigFecha)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.dateTimeEditFechaFecha = QtGui.QDateTimeEdit(self.groupBox_ConfigFecha)
        self.dateTimeEditFechaFecha.setObjectName(_fromUtf8("dateTimeEditFechaFecha"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateTimeEditFechaFecha)
        self.gridLayout.addWidget(self.groupBox_ConfigFecha, 6, 0, 1, 1)
        self.groupBox_ConfigCron = QtGui.QGroupBox(Dialog_ProgramarTarea)
        self.groupBox_ConfigCron.setObjectName(_fromUtf8("groupBox_ConfigCron"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_ConfigCron)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.spinBox_CronAno = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronAno.setMinimum(2016)
        self.spinBox_CronAno.setMaximum(2200)
        self.spinBox_CronAno.setObjectName(_fromUtf8("spinBox_CronAno"))
        self.gridLayout_4.addWidget(self.spinBox_CronAno, 0, 0, 1, 1)
        self.checkBox_HabilitarAnoCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarAnoCron.setObjectName(_fromUtf8("checkBox_HabilitarAnoCron"))
        self.gridLayout_4.addWidget(self.checkBox_HabilitarAnoCron, 0, 1, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_4)
        self.label_19 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spinBox_CronMes = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronMes.setMinimum(1)
        self.spinBox_CronMes.setMaximum(12)
        self.spinBox_CronMes.setObjectName(_fromUtf8("spinBox_CronMes"))
        self.horizontalLayout_5.addWidget(self.spinBox_CronMes)
        self.checkBox_HabilitarMesCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarMesCron.setObjectName(_fromUtf8("checkBox_HabilitarMesCron"))
        self.horizontalLayout_5.addWidget(self.checkBox_HabilitarMesCron)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_13 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.spinBox_CronDia = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronDia.setMinimum(1)
        self.spinBox_CronDia.setMaximum(31)
        self.spinBox_CronDia.setObjectName(_fromUtf8("spinBox_CronDia"))
        self.horizontalLayout_6.addWidget(self.spinBox_CronDia)
        self.checkBox_HabilitarDiaCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarDiaCron.setObjectName(_fromUtf8("checkBox_HabilitarDiaCron"))
        self.horizontalLayout_6.addWidget(self.checkBox_HabilitarDiaCron)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_12 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.spinBox_CronSemana = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronSemana.setMinimum(1)
        self.spinBox_CronSemana.setMaximum(53)
        self.spinBox_CronSemana.setObjectName(_fromUtf8("spinBox_CronSemana"))
        self.horizontalLayout_7.addWidget(self.spinBox_CronSemana)
        self.checkBox_HabilitarSemanaCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarSemanaCron.setObjectName(_fromUtf8("checkBox_HabilitarSemanaCron"))
        self.horizontalLayout_7.addWidget(self.checkBox_HabilitarSemanaCron)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_20 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinBox_CronDiaSemana = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronDiaSemana.setMaximum(7)
        self.spinBox_CronDiaSemana.setObjectName(_fromUtf8("spinBox_CronDiaSemana"))
        self.horizontalLayout_4.addWidget(self.spinBox_CronDiaSemana)
        self.checkBox_HabilitarDiaSemanaCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarDiaSemanaCron.setObjectName(_fromUtf8("checkBox_HabilitarDiaSemanaCron"))
        self.horizontalLayout_4.addWidget(self.checkBox_HabilitarDiaSemanaCron)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_14 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.spinBox_CronHora = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronHora.setMaximum(23)
        self.spinBox_CronHora.setObjectName(_fromUtf8("spinBox_CronHora"))
        self.horizontalLayout_8.addWidget(self.spinBox_CronHora)
        self.checkBox_HabilitarHoraCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarHoraCron.setObjectName(_fromUtf8("checkBox_HabilitarHoraCron"))
        self.horizontalLayout_8.addWidget(self.checkBox_HabilitarHoraCron)
        self.formLayout_2.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_15 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.spinBox_CronMinuto = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronMinuto.setMaximum(59)
        self.spinBox_CronMinuto.setObjectName(_fromUtf8("spinBox_CronMinuto"))
        self.horizontalLayout_9.addWidget(self.spinBox_CronMinuto)
        self.checkBox_HabilitarMinutoCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarMinutoCron.setObjectName(_fromUtf8("checkBox_HabilitarMinutoCron"))
        self.horizontalLayout_9.addWidget(self.checkBox_HabilitarMinutoCron)
        self.formLayout_2.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_16 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.spinBox_CronSegundo = QtGui.QSpinBox(self.groupBox_ConfigCron)
        self.spinBox_CronSegundo.setMaximum(59)
        self.spinBox_CronSegundo.setObjectName(_fromUtf8("spinBox_CronSegundo"))
        self.horizontalLayout_10.addWidget(self.spinBox_CronSegundo)
        self.checkBox_HabilitarSegundoCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarSegundoCron.setObjectName(_fromUtf8("checkBox_HabilitarSegundoCron"))
        self.horizontalLayout_10.addWidget(self.checkBox_HabilitarSegundoCron)
        self.formLayout_2.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_17 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_17)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.dateTimeEdit_CronInicio = QtGui.QDateTimeEdit(self.groupBox_ConfigCron)
        self.dateTimeEdit_CronInicio.setDate(QtCore.QDate(2016, 2, 10))
        self.dateTimeEdit_CronInicio.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2016, 2, 10), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_CronInicio.setCalendarPopup(True)
        self.dateTimeEdit_CronInicio.setObjectName(_fromUtf8("dateTimeEdit_CronInicio"))
        self.gridLayout_5.addWidget(self.dateTimeEdit_CronInicio, 0, 0, 1, 1)
        self.checkBox_HabilitarInicioCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarInicioCron.setObjectName(_fromUtf8("checkBox_HabilitarInicioCron"))
        self.gridLayout_5.addWidget(self.checkBox_HabilitarInicioCron, 0, 1, 1, 1)
        self.formLayout_2.setLayout(8, QtGui.QFormLayout.FieldRole, self.gridLayout_5)
        self.label_18 = QtGui.QLabel(self.groupBox_ConfigCron)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_18)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.dateTimeEdit_CronFin = QtGui.QDateTimeEdit(self.groupBox_ConfigCron)
        self.dateTimeEdit_CronFin.setDate(QtCore.QDate(2016, 2, 10))
        self.dateTimeEdit_CronFin.setMinimumDate(QtCore.QDate(2016, 2, 10))
        self.dateTimeEdit_CronFin.setCalendarPopup(True)
        self.dateTimeEdit_CronFin.setObjectName(_fromUtf8("dateTimeEdit_CronFin"))
        self.gridLayout_6.addWidget(self.dateTimeEdit_CronFin, 0, 0, 1, 1)
        self.checkBox_HabilitarFinCron = QtGui.QCheckBox(self.groupBox_ConfigCron)
        self.checkBox_HabilitarFinCron.setObjectName(_fromUtf8("checkBox_HabilitarFinCron"))
        self.gridLayout_6.addWidget(self.checkBox_HabilitarFinCron, 0, 1, 1, 1)
        self.formLayout_2.setLayout(9, QtGui.QFormLayout.FieldRole, self.gridLayout_6)
        self.gridLayout.addWidget(self.groupBox_ConfigCron, 4, 0, 1, 1)
        self.groupBox_ConfigInterval = QtGui.QGroupBox(Dialog_ProgramarTarea)
        self.groupBox_ConfigInterval.setObjectName(_fromUtf8("groupBox_ConfigInterval"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_ConfigInterval)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox_IntervalSemanas = QtGui.QSpinBox(self.groupBox_ConfigInterval)
        self.spinBox_IntervalSemanas.setMaximum(9999)
        self.spinBox_IntervalSemanas.setObjectName(_fromUtf8("spinBox_IntervalSemanas"))
        self.gridLayout_3.addWidget(self.spinBox_IntervalSemanas, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBox_IntervalDias = QtGui.QSpinBox(self.groupBox_ConfigInterval)
        self.spinBox_IntervalDias.setMaximum(9999)
        self.spinBox_IntervalDias.setObjectName(_fromUtf8("spinBox_IntervalDias"))
        self.gridLayout_3.addWidget(self.spinBox_IntervalDias, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.spinBox_IntervalHoras = QtGui.QSpinBox(self.groupBox_ConfigInterval)
        self.spinBox_IntervalHoras.setMaximum(9999)
        self.spinBox_IntervalHoras.setObjectName(_fromUtf8("spinBox_IntervalHoras"))
        self.gridLayout_3.addWidget(self.spinBox_IntervalHoras, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.spinBox_IntervalMinutos = QtGui.QSpinBox(self.groupBox_ConfigInterval)
        self.spinBox_IntervalMinutos.setMaximum(999999)
        self.spinBox_IntervalMinutos.setObjectName(_fromUtf8("spinBox_IntervalMinutos"))
        self.gridLayout_3.addWidget(self.spinBox_IntervalMinutos, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.spinBox_IntervalSegundos = QtGui.QSpinBox(self.groupBox_ConfigInterval)
        self.spinBox_IntervalSegundos.setMaximum(9999999)
        self.spinBox_IntervalSegundos.setObjectName(_fromUtf8("spinBox_IntervalSegundos"))
        self.gridLayout_3.addWidget(self.spinBox_IntervalSegundos, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dateTimeEdit_IntervalInicio = QtGui.QDateTimeEdit(self.groupBox_ConfigInterval)
        self.dateTimeEdit_IntervalInicio.setObjectName(_fromUtf8("dateTimeEdit_IntervalInicio"))
        self.horizontalLayout.addWidget(self.dateTimeEdit_IntervalInicio)
        self.checkBox_HabilitarInicioInterval = QtGui.QCheckBox(self.groupBox_ConfigInterval)
        self.checkBox_HabilitarInicioInterval.setObjectName(_fromUtf8("checkBox_HabilitarInicioInterval"))
        self.horizontalLayout.addWidget(self.checkBox_HabilitarInicioInterval)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_ConfigInterval)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dateTimeEdit_IntervalFin = QtGui.QDateTimeEdit(self.groupBox_ConfigInterval)
        self.dateTimeEdit_IntervalFin.setObjectName(_fromUtf8("dateTimeEdit_IntervalFin"))
        self.gridLayout_2.addWidget(self.dateTimeEdit_IntervalFin, 0, 0, 1, 1)
        self.checkBox_HabilitarFinInterval = QtGui.QCheckBox(self.groupBox_ConfigInterval)
        self.checkBox_HabilitarFinInterval.setObjectName(_fromUtf8("checkBox_HabilitarFinInterval"))
        self.gridLayout_2.addWidget(self.checkBox_HabilitarFinInterval, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_ConfigInterval, 5, 0, 1, 1)
        self.comboBox_Tareas = QtGui.QComboBox(Dialog_ProgramarTarea)
        self.comboBox_Tareas.setObjectName(_fromUtf8("comboBox_Tareas"))
        self.gridLayout.addWidget(self.comboBox_Tareas, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_ProgramarTarea)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_Tipo = QtGui.QComboBox(Dialog_ProgramarTarea)
        self.comboBox_Tipo.setObjectName(_fromUtf8("comboBox_Tipo"))
        self.comboBox_Tipo.addItem(_fromUtf8(""))
        self.comboBox_Tipo.addItem(_fromUtf8(""))
        self.comboBox_Tipo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Tipo, 3, 0, 1, 1)
        self.pushButton_Guardar = QtGui.QPushButton(Dialog_ProgramarTarea)
        self.pushButton_Guardar.setObjectName(_fromUtf8("pushButton_Guardar"))
        self.gridLayout.addWidget(self.pushButton_Guardar, 7, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog_ProgramarTarea)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog_ProgramarTarea)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ProgramarTarea)

    def retranslateUi(self, Dialog_ProgramarTarea):
        Dialog_ProgramarTarea.setWindowTitle(_translate("Dialog_ProgramarTarea", "Programar Tarea", None))
        self.groupBox_ConfigFecha.setTitle(_translate("Dialog_ProgramarTarea", "Configuracion", None))
        self.label_3.setText(_translate("Dialog_ProgramarTarea", "Fecha", None))
        self.groupBox_ConfigCron.setTitle(_translate("Dialog_ProgramarTarea", "Configuracion", None))
        self.label_4.setText(_translate("Dialog_ProgramarTarea", "Año", None))
        self.checkBox_HabilitarAnoCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_19.setText(_translate("Dialog_ProgramarTarea", "Mes", None))
        self.spinBox_CronMes.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (1-12) 0 = Disabled", None))
        self.checkBox_HabilitarMesCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_13.setText(_translate("Dialog_ProgramarTarea", "Dia", None))
        self.spinBox_CronDia.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (1-31) 0 = Disabled", None))
        self.checkBox_HabilitarDiaCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_12.setText(_translate("Dialog_ProgramarTarea", "Semana", None))
        self.spinBox_CronSemana.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (1-53) 0 = Disabled", None))
        self.checkBox_HabilitarSemanaCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_20.setText(_translate("Dialog_ProgramarTarea", "Dia Semana", None))
        self.spinBox_CronDiaSemana.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (0-6)", None))
        self.checkBox_HabilitarDiaSemanaCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_14.setText(_translate("Dialog_ProgramarTarea", "Hora", None))
        self.spinBox_CronHora.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (0-23) 0 = Disabled", None))
        self.checkBox_HabilitarHoraCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_15.setText(_translate("Dialog_ProgramarTarea", "Minuto", None))
        self.spinBox_CronMinuto.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (0-59) 0 = Disabled", None))
        self.checkBox_HabilitarMinutoCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_16.setText(_translate("Dialog_ProgramarTarea", "Segundo", None))
        self.spinBox_CronSegundo.setToolTip(_translate("Dialog_ProgramarTarea", "Rango (0-59) 0 = Disabled", None))
        self.checkBox_HabilitarSegundoCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_17.setText(_translate("Dialog_ProgramarTarea", "Inicio", None))
        self.checkBox_HabilitarInicioCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_18.setText(_translate("Dialog_ProgramarTarea", "Fin", None))
        self.checkBox_HabilitarFinCron.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.groupBox_ConfigInterval.setTitle(_translate("Dialog_ProgramarTarea", "Configuracion", None))
        self.label_5.setText(_translate("Dialog_ProgramarTarea", "Semanas", None))
        self.label_6.setText(_translate("Dialog_ProgramarTarea", "Dias", None))
        self.label_7.setText(_translate("Dialog_ProgramarTarea", "Horas", None))
        self.label_8.setText(_translate("Dialog_ProgramarTarea", "Minutos", None))
        self.label_9.setText(_translate("Dialog_ProgramarTarea", "Segundos", None))
        self.label_10.setText(_translate("Dialog_ProgramarTarea", "Inicio", None))
        self.checkBox_HabilitarInicioInterval.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_11.setText(_translate("Dialog_ProgramarTarea", "Fin", None))
        self.checkBox_HabilitarFinInterval.setText(_translate("Dialog_ProgramarTarea", "Habilitar", None))
        self.label_2.setText(_translate("Dialog_ProgramarTarea", "Tipo", None))
        self.comboBox_Tipo.setItemText(0, _translate("Dialog_ProgramarTarea", "Fecha", None))
        self.comboBox_Tipo.setItemText(1, _translate("Dialog_ProgramarTarea", "Cronometro", None))
        self.comboBox_Tipo.setItemText(2, _translate("Dialog_ProgramarTarea", "Intervalo", None))
        self.pushButton_Guardar.setText(_translate("Dialog_ProgramarTarea", "Guardar", None))
        self.label.setText(_translate("Dialog_ProgramarTarea", "Tarea", None))

import recursos_rc
